project:
  type: website
  resources:
  - "IC_EX/**/*.png"

website:
  title: "Chart Whisperer"
  
  navbar:
    pinned: true 
    left:
      - icon: rocket-takeoff-fill
        text: "Adventure"
        href: "outputs.html"
      - icon: terminal-fill
        text: "Powered By"
        href: "techstack.html"
        
    right:
      - icon: info-circle-fill
        href: "about.html"
        aria-label: "About"
      - icon: linkedin
        href: "https://linkedin.com/in/cjancheta" 
        aria-label: "LinkedIn"
        
  page-footer: 
    right: "Charles Jr Ancheta | Visual Analytics & Applications"
      
format:
  html:
    theme: cyborg
    css: styles.css
    code-overflow: scroll
    code-line-numbers: true
    fig-align: center
    toc: false