{
  "hash": "4a5c0277309b4e40e3d5d554440a3d86",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Visual Analytics for Data Discovery\"\nsubtitle: \"Mythbusting risk stereotypes in a motor insurance portfolio\"\ndate: \"18 May 2026\"\ndate-modified: \"last-modified\"\neditor: visual\nexecute:\n  freeze: auto\n  echo: true\n  eval: true\n  warning: false\n  message: false\nformat:\n  html:\n    code-fold: true\n    code-overflow: scroll\n    code-summary: \"Show the code\"\n    code-line-numbers: false\n---\n\n# 1 Introduction\n\n## 1.1 Background\n\nMotor insurers need to know whether poor portfolio results come from a broad deterioration or from a small number of identifiable risk segments. A single loss-ratio total is not sufficient because claim frequency, claim severity, exposure duration, policy design, customer loyalty, vehicle profile, and geography can all produce different underwriting implications.\n\nThis report uses visual analytics to investigate a Spanish motor insurance portfolio observed from 2022 to 2024. The analysis is framed as a mythbusting exercise: common stereotypes about insurance risk are tested against the data. The objective is not to build a pricing model. The objective is to discover which beliefs are supported by evidence, which are myths, and which are only partially true.\n\n## 1.2 Analytical Objective\n\nThe analysis is organised around 10 research questions aligned with three strategic objectives:\n\n1. **Maximise overall portfolio profitability** by identifying segments where loss ratio, claim frequency, claim severity, or underwriting result point to adverse performance.\n2. **Maximise retention and loyalty among low-risk, highly profitable customers** by testing whether longer-observed customers and favourable behavioural signals are associated with better profitability.\n3. **Identify high-risk segments for appropriately calibrated premium pricing** by separating stereotypes from evidence-backed signals that can support pricing, excess, coverage, renewal, or monitoring actions.\n\nThis makes the data wrangling purposeful: only variables needed to test a myth are retained, recoded, or derived. The guiding visual communication principle is **one-look interpretation**. Static charts, small multiples, and dashboards are preferred over animations because stakeholders should be able to compare segments without relying on memory.\n\n## 1.3 Data Sources\n\nTwo source files are used:\n\n- `data/Dataset of motor insurance portfolio.csv`: policy-year motor insurance records.\n- `data/Descriptive of variables.xlsx`: variable descriptions and code definitions.\n\nEach row is a policy-year observation. The same insured policy can appear in more than one year.\n\n# 2 Getting Started\n\n## 2.1 R Packages\n\nThe package set is selected for reproducible data wrangling, static ggplot-based visual analytics, distribution-aware plots, and statistical validation.\n\n| Package | Purpose |\n|---|---|\n| `tidyverse` | Import, wrangling, plotting, and factor handling. |\n| `readxl` | Import the Excel data dictionary. |\n| `knitr` | Render compact summary tables. |\n| `scales` | Format percentages, currency, and large numbers. |\n| `patchwork` | Combine related plots into one-look dashboards. |\n| `ggdist` | Half-eye and point-interval plots for distributions and uncertainty. |\n| `ggridges` | Ridgeline density plots for ordered-group comparisons. |\n| `ggpubr` | Statistical annotations on selected ggplot charts. |\n| `ggstatsplot` | Statistical ggplot extensions such as `ggbarstats()` and `ggbetweenstats()`. |\n| `viridis` | Colour-blind-friendly palettes. |\n| `broom` | Tidy statistical test results. |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  tidyverse, readxl, knitr, scales,\n  patchwork, ggdist, ggridges,\n  ggpubr, ggstatsplot, viridis, broom\n)\n\nif (\"package:ggtern\" %in% search()) {\n  detach(\"package:ggtern\", unload = TRUE, character.only = TRUE)\n}\n\ntheme_set(ggplot2::theme_minimal(base_size = 11))\n\ntheme_update(\n  plot.title = element_text(face = \"bold\"),\n  plot.subtitle = element_text(colour = \"grey35\"),\n  panel.grid.minor = element_blank(),\n  legend.position = \"bottom\",\n  tern.axis.ticks.length.major = rel(0.5),\n  tern.axis.ticks.length.minor = rel(0.25)\n)\n\nsafe_divide <- function(numerator, denominator) {\n  if_else(denominator > 0, numerator / denominator, NA_real_)\n}\n```\n:::\n\n\n## 2.2 Importing the Data\n\nThe CSV file is semicolon-delimited, so the delimiter is stated explicitly to prevent silent parsing errors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio_raw <- read_delim(\n  file = \"data/Dataset of motor insurance portfolio.csv\",\n  delim = \";\",\n  show_col_types = FALSE\n)\n\ndictionary_raw <- read_excel(\"data/Descriptive of variables.xlsx\")\n\nglimpse(portfolio_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Rows:\", comma(nrow(portfolio_raw)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Columns:\", ncol(portfolio_raw), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nColumns: 47 \n```\n\n\n:::\n:::\n\n\n# 3 Research Questions and Feature Map\n\nThe report uses exactly 10 research questions. Each question starts with an insurance stereotype, then tests whether the stereotype is real, a myth, or mixed. The questions bridge univariate distribution analysis with bivariate profitability analysis by first asking how common each segment is, then asking whether that segment is profitable.\n\n| No. | Myth to test | Research question | Coverage dimension | Useful features | Best-fit visual method |\n|---:|---|---|---|---|---|\n| 1 | Young drivers are always the worst risks. | Are younger drivers genuinely less profitable than older drivers? | Conventional and demographic | `driver_age_band`, claims, exposure, loss ratio | Ordered KPI bars and ridgeline distribution |\n| 2 | Older vehicles are always riskier. | Does vehicle age increase loss ratio and claim frequency? | Conventional and vehicle factor | `vehicle_age_band`, claims, exposure, loss ratio | Ranked bars and age interaction heatmap |\n| 3 | Comprehensive policies are safer because customers pay more. | Which policy types create the most profitability pressure? | Product and coverage design | `policy_type`, premium, incurred, claims | Ranked bars and profitability-status bars |\n| 4 | Premium brands are the biggest loss drivers. | Are premium vehicle brands less profitable than mainstream brands? | Brand-and-status | `brand_tier`, claim severity, loss ratio | Point interval and severity comparison |\n| 5 | Higher vehicle value always means poorer profitability. | Does vehicle value show a monotonic relationship with loss ratio? | Brand-and-status | `vehicle_value_band`, premium, incurred, claims | Ordered KPI bars |\n| 6 | Bad bonus-score customers are always the worst. | Does bonus score separate profitable and unprofitable customers? | Behavioural and claim history proxy | `bonus_score`, loss ratio, claim frequency | Half-eye + boxplot + aggregate point |\n| 7 | Short-term policies are harmless because exposure is small. | Are short-exposure policies a hidden profitability problem? | Behavioural and exposure pattern | `exposure_band`, loss ratio, cancellation | Ridgeline density with quantile shading |\n| 8 | Loyal customers are just retained volume, not necessarily profitable. | Are longer-observed customers more profitable and worth retaining? | Loyalty and retention | `loyalty_band`, premium, incurred, cancellation | Ranked KPI bars |\n| 9 | Cancelled policies are removed risks, so cancellation is good. | Are cancelled policies actually worse risks than active policies? | Loyalty and policy status | `policy_status`, loss ratio, claim frequency | Stacked bars and density comparison |\n| 10 | Urban areas are always worse than rural areas. | Does geography materially affect frequency, severity, and loss ratio? | Geographic | `circulation_area`, `municipality_type`, `geo_segment` | Point intervals and geography bars |\n\nThe selected methods emphasise practical interpretation. A myth is treated as **real** only when the segment has a visible adverse pattern and a meaningful profitability implication. A myth is **busted** when the common stereotype is contradicted by loss ratio, frequency, severity, or materiality. A myth is **mixed** when the stereotype is true for one risk dimension but not for overall profitability.\n\n## 3.1 Visual Analytics Technique Selection Rationale\n\nThe visual analytics methods are selected to serve the three strategic objectives. The report therefore avoids using charts only because they are visually interesting. Each method is chosen because it answers a specific underwriting decision question.\n\n| Strategic objective | Analytical need | Technique selected | Rationale |\n|---|---|---|---|\n| Maximise portfolio profitability | Identify which segments are unprofitable and whether the issue is material | `geom_tile()` + `geom_text()` KPI matrices with break-even references where needed | Tile matrices make loss ratio, claim frequency, severity, and premium share comparable without using unsupported bar layers. |\n| Maximise portfolio profitability | Diagnose whether poor results come from frequency, severity, or both | KPI matrices and `stat_pointinterval()` | These methods show frequency, severity, and uncertainty while staying inside the approved ggplot technique set. |\n| Retain low-risk profitable customers | Compare loyalty groups and identify profitable retained segments | `geom_tile()` + `geom_text()` KPI matrices for `loyalty_band` and bonus score | KPI matrices connect retention directly to loss ratio and premium share, showing whether loyal customers are profitable enough to protect. |\n| Retain low-risk profitable customers | Avoid blunt rules that penalise good customers inside broad segments | `stat_halfeye()` + `geom_boxplot()` + pairwise Wilcoxon or `ggbetweenstats()` | Distribution-aware plots show overlap within groups, preventing overconfidence in stereotypes such as age, bonus score, or brand status. |\n| Calibrate premium pricing | Detect hidden tail-risk patterns in short exposure or claimant groups | `geom_density_ridges_gradient()` with quantile shading | Ridgelines compare distribution shape across ordered groups and reveal whether a segment has a heavier adverse tail rather than just a higher mean. |\n| Calibrate premium pricing | Identify interaction risk that univariate charts may hide | `geom_tile()` heatmaps with embedded labels | Heatmaps make two-way combinations, such as driver age by vehicle age, readable at a glance and useful for pricing segmentation. |\n| Calibrate premium pricing | Assess dense numerical signals such as power-to-weight | `geom_hex()` + `geom_smooth(method = \"gam\")` | Hexbin plots avoid overplotting in large policy-level data, while the GAM smoother shows whether a practical non-linear pattern exists. |\n| Reproducibility and communication | Test categorical myths with statistical context | `ggbarstats()` and `ggbetweenstats()` | These approved ggplot extensions combine visual comparison with statistical evidence for categorical and numeric segment differences. |\n\nThese choices also support the mythbusting structure. A myth is not confirmed by one chart alone; it is judged by the combined evidence of segment size, loss ratio, claim frequency, claim severity, and business relevance.\n\n# 4 Data Wrangling\n\n## 4.1 Data Quality Checks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquality_checks <- tibble(\n  check = c(\n    \"Duplicated rows\",\n    \"Rows with missing vehicle age\",\n    \"Rows with missing licence age\",\n    \"Rows with missing fuel type\",\n    \"Rows with missing vehicle value\",\n    \"Rows with non-positive exposure\",\n    \"Rows with non-positive total premium\"\n  ),\n  count = c(\n    sum(duplicated(portfolio_raw)),\n    sum(is.na(portfolio_raw$vehicle_age)),\n    sum(is.na(portfolio_raw$age_driving_licence)),\n    sum(is.na(portfolio_raw$fuel_type)),\n    sum(is.na(portfolio_raw$vehicle_value)),\n    sum(portfolio_raw$total_exposure <= 0, na.rm = TRUE),\n    sum(portfolio_raw$total_premium <= 0, na.rm = TRUE)\n  )\n)\n\nquality_checks |>\n  mutate(count = comma(count)) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|check                                |count |\n|:------------------------------------|:-----|\n|Duplicated rows                      |0     |\n|Rows with missing vehicle age        |2     |\n|Rows with missing licence age        |2     |\n|Rows with missing fuel type          |1,287 |\n|Rows with missing vehicle value      |513   |\n|Rows with non-positive exposure      |49    |\n|Rows with non-positive total premium |49    |\n\n\n:::\n:::\n\n\nThe missingness is limited to selected driver and vehicle attributes. These rows are retained because claim, premium, and exposure outcomes remain useful. Unknown or missing categorical values are labelled where necessary rather than removed globally.\n\n## 4.2 Feature Selection and Recoding\n\nOnly variables needed for the 10 research questions are retained. Raw code values are recoded into stakeholder-readable labels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npremium_brands <- c(\n  \"AUDI\", \"BMW\", \"FERRARI\", \"HUMMER\", \"INFINITI\", \"JAGUAR\",\n  \"LAND ROVER\", \"LEXUS\", \"MASERATI\", \"MERCEDES\", \"MINI\",\n  \"PORSCHE\", \"SAAB\", \"VOLVO\"\n)\n\nportfolio <- portfolio_raw |>\n  select(\n    insured_id, year,\n    policy_type, policy_status, business_type, payment_frequency, bonus_score,\n    driver_age, vehicle_age, fuel_type, vehicle_value, power_to_weight_ratio,\n    vehicle_brand, municipality_type, circulation_area,\n    total_premium, total_claims, total_incurred, total_exposure\n  ) |>\n  mutate(\n    policy_type = recode(\n      policy_type,\n      \"TP\" = \"Third party\",\n      \"TPG\" = \"Third party + glass\",\n      \"CC\" = \"Third party + add-ons\",\n      \"COMP_E\" = \"Comprehensive with excess\",\n      \"COMP_N\" = \"Comprehensive without excess\"\n    ),\n    policy_type = factor(\n      policy_type,\n      levels = c(\n        \"Third party\", \"Third party + glass\", \"Third party + add-ons\",\n        \"Comprehensive with excess\", \"Comprehensive without excess\"\n      )\n    ),\n    policy_status = recode(policy_status, \"A\" = \"Active\", \"C\" = \"Cancelled\"),\n    business_type = recode(business_type, \"NB\" = \"New business\", \"P\" = \"Portfolio\"),\n    payment_frequency = recode(\n      payment_frequency,\n      \"A\" = \"Annual\", \"S\" = \"Semiannual\", \"Q\" = \"Quarterly\"\n    ),\n    bonus_score = recode(bonus_score, \"G\" = \"Good\", \"N\" = \"Neutral\", \"B\" = \"Bad\"),\n    bonus_score = factor(bonus_score, levels = c(\"Good\", \"Neutral\", \"Bad\")),\n    fuel_type = recode(fuel_type, \"D\" = \"Diesel\", \"G\" = \"Gasoline\", .missing = \"Unknown\"),\n    municipality_type = recode(\n      municipality_type,\n      \"I\" = \"Inland\", \"C\" = \"Coastal\", \"IS\" = \"Islands\"\n    ),\n    circulation_area = recode(circulation_area, \"U\" = \"Urban\", \"R\" = \"Rural\"),\n    vehicle_brand = replace_na(vehicle_brand, \"Unknown\"),\n    brand_tier = if_else(vehicle_brand %in% premium_brands, \"Premium brand\", \"Mainstream brand\"),\n    geo_segment = str_c(municipality_type, \" - \", circulation_area),\n    across(\n      c(\n        policy_status, business_type, payment_frequency, fuel_type,\n        municipality_type, circulation_area, vehicle_brand, brand_tier, geo_segment\n      ),\n      as_factor\n    )\n  )\n```\n:::\n\n\n## 4.3 Derived Analytical Variables\n\nLoss ratio is used as the main profitability metric. Claim frequency and claim severity are separated because the underwriting action differs when a segment is high-frequency versus high-severity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio <- portfolio |>\n  mutate(\n    loss_ratio = safe_divide(total_incurred, total_premium),\n    underwriting_result = total_premium - total_incurred,\n    claim_flag = total_claims > 0,\n    claim_frequency = safe_divide(total_claims, total_exposure),\n    claim_severity = safe_divide(total_incurred, total_claims),\n    profit_status = case_when(\n      total_claims == 0 ~ \"No claim\",\n      loss_ratio <= 1 ~ \"Claim, still profitable\",\n      TRUE ~ \"Loss-making\"\n    ),\n    profit_status = factor(\n      profit_status,\n      levels = c(\"Loss-making\", \"Claim, still profitable\", \"No claim\")\n    ),\n    exposure_band = cut(\n      total_exposure,\n      breaks = c(0, 0.35, 0.75, 0.95, Inf),\n      labels = c(\"Very short (<0.35)\", \"Short (0.35-0.75)\", \"Medium (0.75-0.95)\", \"Full (>0.95)\"),\n      include.lowest = TRUE\n    ),\n    driver_age_band = cut(\n      driver_age,\n      breaks = c(17, 25, 35, 45, 55, 65, Inf),\n      labels = c(\"18-25\", \"26-35\", \"36-45\", \"46-55\", \"56-65\", \"66+\"),\n      right = TRUE\n    ),\n    vehicle_age_band = cut(\n      vehicle_age,\n      breaks = c(-Inf, 3, 7, 12, 20, Inf),\n      labels = c(\"0-3\", \"4-7\", \"8-12\", \"13-20\", \"21+\"),\n      right = TRUE\n    ),\n    vehicle_value_band = ntile(vehicle_value, 5),\n    vehicle_value_band = factor(\n      vehicle_value_band,\n      labels = c(\"Lowest\", \"Low\", \"Middle\", \"High\", \"Highest\")\n    ),\n    same_insured_years = ave(\n      year,\n      insured_id,\n      FUN = function(x) length(unique(x))\n    ),\n    loyalty_band = case_when(\n      same_insured_years >= 3 ~ \"Observed all 3 years\",\n      same_insured_years == 2 ~ \"Observed 2 years\",\n      TRUE ~ \"Observed 1 year\"\n    ),\n    loyalty_band = factor(\n      loyalty_band,\n      levels = c(\"Observed 1 year\", \"Observed 2 years\", \"Observed all 3 years\")\n    )\n  )\n\nloss_ratio_cap_99 <- quantile(\n  portfolio$loss_ratio[is.finite(portfolio$loss_ratio)],\n  probs = 0.99,\n  na.rm = TRUE\n)\n\nportfolio <- portfolio |>\n  mutate(loss_ratio_capped_99 = pmin(loss_ratio, loss_ratio_cap_99))\n```\n:::\n\n\n## 4.4 Helper Summary Tables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsegment_summary <- function(data, segment_var) {\n  data |>\n    filter(!is.na({{ segment_var }})) |>\n    group_by({{ segment_var }}) |>\n    summarise(\n      policies = n(),\n      exposure = sum(total_exposure, na.rm = TRUE),\n      premium = sum(total_premium, na.rm = TRUE),\n      claims = sum(total_claims, na.rm = TRUE),\n      incurred = sum(total_incurred, na.rm = TRUE),\n      underwriting_result = sum(underwriting_result, na.rm = TRUE),\n      loss_ratio = incurred / premium,\n      claim_frequency = claims / exposure,\n      claim_severity = incurred / claims,\n      claim_rate = mean(claim_flag, na.rm = TRUE),\n      .groups = \"drop\"\n    ) |>\n    arrange(desc(premium))\n}\n\nportfolio_summary <- portfolio |>\n  summarise(\n    policy_years = n(),\n    insured_policies = n_distinct(insured_id),\n    exposure = sum(total_exposure, na.rm = TRUE),\n    premium = sum(total_premium, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    incurred = sum(total_incurred, na.rm = TRUE),\n    underwriting_result = sum(underwriting_result, na.rm = TRUE),\n    loss_ratio = incurred / premium,\n    claim_frequency = claims / exposure,\n    claim_severity = incurred / claims\n  )\n\nyear_summary <- segment_summary(portfolio, year)\npolicy_type_summary <- segment_summary(portfolio, policy_type)\nbusiness_summary <- segment_summary(portfolio, business_type)\nbonus_summary <- segment_summary(portfolio, bonus_score)\nexposure_summary <- segment_summary(portfolio, exposure_band)\ndriver_age_summary <- segment_summary(portfolio, driver_age_band)\nvehicle_age_summary <- segment_summary(portfolio, vehicle_age_band)\nvehicle_value_summary <- segment_summary(portfolio, vehicle_value_band)\nbrand_tier_summary <- segment_summary(portfolio, brand_tier)\nloyalty_summary <- segment_summary(portfolio, loyalty_band)\ngeo_summary <- segment_summary(portfolio, geo_segment)\n\nportfolio_summary |>\n  transmute(\n    `Policy-years` = comma(policy_years),\n    `Insured policies` = comma(insured_policies),\n    Exposure = comma(exposure, accuracy = 1),\n    Premium = dollar(premium, prefix = \"\"),\n    Incurred = dollar(incurred, prefix = \"\"),\n    `Underwriting result` = dollar(underwriting_result, prefix = \"\"),\n    `Loss ratio` = percent(loss_ratio, accuracy = 0.1),\n    `Claim frequency` = number(claim_frequency, accuracy = 0.001),\n    `Claim severity` = dollar(claim_severity, prefix = \"\")\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Policy-years |Insured policies |Exposure |Premium     |Incurred   |Underwriting result |Loss ratio |Claim frequency |Claim severity |\n|:------------|:----------------|:--------|:-----------|:----------|:-------------------|:----------|:---------------|:--------------|\n|354,140      |185,678          |250,326  |105,079,669 |73,864,811 |31,214,859          |70.3%      |0.308           |958.05         |\n\n\n:::\n:::\n\n\nThe overall portfolio loss ratio is 70.3%, with 354,140 policy-year records and 77,099 claims.\n\n# 5 Exploratory Data Analysis\n\n## 5.1 Portfolio at a Glance\n\n**Research questions supported:** RQ1 and RQ2.\n\n**Technique justification:** A patchwork dashboard combines the year trend, loss ratio, claim frequency, and underwriting result in one view. This is more intuitive than separate charts because the reader can immediately see whether deterioration is caused by loss ratio movement, claim frequency movement, or exposure scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_long <- year_summary |>\n  select(year, premium, incurred, underwriting_result, loss_ratio, claim_frequency, exposure) |>\n  pivot_longer(\n    cols = c(premium, incurred, underwriting_result, loss_ratio, claim_frequency, exposure),\n    names_to = \"measure\",\n    values_to = \"value\"\n  ) |>\n  mutate(\n    measure = recode(\n      measure,\n      \"premium\" = \"Premium\",\n      \"incurred\" = \"Incurred loss\",\n      \"underwriting_result\" = \"Underwriting result\",\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\",\n      \"exposure\" = \"Exposure\"\n    ),\n    label = case_when(\n      measure %in% c(\"Loss ratio\") ~ percent(value, accuracy = 0.1),\n      measure %in% c(\"Claim frequency\") ~ number(value, accuracy = 0.001),\n      TRUE ~ label_number(scale_cut = cut_short_scale())(value)\n    )\n  )\n\nggplot(year_long, aes(x = factor(year), y = measure, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(aes(label = label), size = 3.2) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number(scale_cut = cut_short_scale())) +\n  labs(\n    title = \"Portfolio dashboard by year\",\n    subtitle = \"Tile values keep profitability, frequency, materiality, and financial outcome visible at once\",\n    x = \"Year\",\n    y = NULL,\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-8-1.png){width=1152}\n:::\n:::\n\n\n**What this tells us:** The full 2022-2024 history is visible at once. The dashboard separates scale, profitability, and frequency so deterioration can be interpreted as a portfolio-management problem rather than as a single unexplained loss-ratio number.\n\n## 5.2 Executive Triage Map\n\n**Research questions supported:** RQ1 and RQ2.\n\n**Technique justification:** A KPI tile matrix replaces the earlier bubble map so the visual stays within the approved technique list. Claim frequency, claim severity, loss ratio, and premium share are shown together to preserve the triage logic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntriage_tbl <- policy_type_summary |>\n  mutate(\n    premium_share = premium / sum(premium)\n  ) |>\n  select(policy_type, loss_ratio, claim_frequency, claim_severity, premium_share) |>\n  pivot_longer(-policy_type, names_to = \"metric\", values_to = \"value\") |>\n  mutate(\n    metric = recode(\n      metric,\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\",\n      \"claim_severity\" = \"Claim severity\",\n      \"premium_share\" = \"Premium share\"\n    ),\n    label = case_when(\n      metric == \"Claim severity\" ~ dollar(value, prefix = \"\"),\n      metric == \"Claim frequency\" ~ number(value, accuracy = 0.001),\n      TRUE ~ percent(value, accuracy = 0.1)\n    )\n  )\n\nggplot(triage_tbl, aes(x = metric, y = policy_type, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(aes(label = label), size = 3.1) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number(scale_cut = cut_short_scale())) +\n  labs(\n    title = \"Policy-type triage: frequency, severity, profitability, materiality\",\n    x = NULL,\n    y = NULL,\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-9-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** The chart separates frequency problems from severity problems. A policy type with high severity but low frequency needs a different response from a policy type with persistent high claim frequency.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_type_summary |>\n  mutate(review_priority = dense_rank(desc(loss_ratio + claim_frequency + premium / max(premium)))) |>\n  arrange(review_priority) |>\n  transmute(\n    Priority = review_priority,\n    `Policy type` = policy_type,\n    Premium = dollar(premium, prefix = \"\"),\n    `Loss ratio` = percent(loss_ratio, accuracy = 0.1),\n    `Claim frequency` = number(claim_frequency, accuracy = 0.001),\n    `Claim severity` = dollar(claim_severity, prefix = \"\"),\n    `Suggested action` = case_when(\n      loss_ratio >= 1 ~ \"Immediate pricing and coverage review\",\n      claim_frequency >= portfolio_summary$claim_frequency ~ \"Frequency management and renewal monitoring\",\n      claim_severity >= portfolio_summary$claim_severity ~ \"Severity reserve and claims review\",\n      TRUE ~ \"Monitor as lower priority\"\n    )\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| Priority|Policy type                  |Premium    |Loss ratio |Claim frequency |Claim severity |Suggested action                            |\n|--------:|:----------------------------|:----------|:----------|:---------------|:--------------|:-------------------------------------------|\n|        1|Comprehensive without excess |10,344,550 |93.9%      |1.046           |752.25         |Frequency management and renewal monitoring |\n|        2|Comprehensive with excess    |35,712,392 |73.8%      |0.410           |988.01         |Frequency management and renewal monitoring |\n|        3|Third party + add-ons        |49,801,769 |63.4%      |0.221           |991.26         |Severity reserve and claims review          |\n|        4|Third party + glass          |8,201,409  |69.2%      |0.207           |1,099.97       |Severity reserve and claims review          |\n|        5|Third party                  |1,019,549  |54.3%      |0.133           |1,091.59       |Severity reserve and claims review          |\n\n\n:::\n:::\n\n\n# 6 Univariate Analysis\n\n## 6.1 Portfolio Composition\n\n**Research questions supported:** RQ1, RQ3, RQ4, RQ6, and RQ10.\n\n**Technique justification:** `ggbarstats()` is used because it is one of the approved visual methods and it combines categorical composition with an association test. This makes the univariate-to-bivariate bridge explicit: policy type is shown together with profitability status.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbarstats(\n  data = portfolio,\n  x = policy_type,\n  y = profit_status,\n  label = \"percentage\",\n  results.subtitle = FALSE,\n  title = \"Policy type composition by profitability status\",\n  xlab = \"Policy type\",\n  ylab = \"Policy-year records\",\n  legend.title = \"Profitability status\"\n) +\n  theme(axis.text.x = element_text(angle = 25, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-11-1.png){width=1152}\n:::\n:::\n\n\n**What this tells us:** The portfolio is not evenly distributed across segments. This matters because a high loss ratio in a tiny segment should not be interpreted the same way as a moderate loss ratio in a large premium segment.\n\n## 6.2 Numerical Feature Distributions\n\n**Research questions supported:** RQ7, RQ8, and RQ9.\n\n**Technique justification:** Histograms with free scales show the empirical shape of numeric risk features. Vehicle value is shown on a log scale because the distribution is strongly right-skewed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumeric_long <- portfolio |>\n  transmute(\n    `Driver age` = driver_age,\n    `Vehicle age` = vehicle_age,\n    `Power-to-weight ratio` = power_to_weight_ratio,\n    `Vehicle value` = vehicle_value\n  ) |>\n  pivot_longer(everything(), names_to = \"feature\", values_to = \"value\") |>\n  filter(!is.na(value), value > 0)\n\nggplot(numeric_long, aes(value)) +\n  geom_histogram(bins = 35, fill = \"#4C78A8\", colour = \"white\") +\n  facet_wrap(~ feature, scales = \"free\", ncol = 2) +\n  scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +\n  labs(\n    title = \"Distribution of continuous risk features\",\n    x = NULL,\n    y = \"Policy-year records\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-12-1.png){width=1152}\n:::\n:::\n\n\n**What this tells us:** Vehicle value and power-to-weight are skewed, so later charts use log scales, hexbin density, or capped outcome variables rather than relying on raw scatterplots.\n\n## 6.3 Claim and Profitability Status\n\n**Research questions supported:** RQ1 and RQ2.\n\n**Technique justification:** A stacked proportional bar is used because the business question is not only \"which segment has claims?\" but \"which segment has loss-making claims after premium is considered?\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbarstats(\n  data = portfolio,\n  x = policy_type,\n  y = profit_status,\n  label = \"percentage\",\n  results.subtitle = FALSE,\n  title = \"Profitability status by policy type\",\n  xlab = \"Policy type\",\n  ylab = \"Policy-year records\",\n  legend.title = \"Profitability status\"\n) +\n  theme(axis.text.x = element_text(angle = 25, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n**What this tells us:** The stacked structure shows whether a policy type has many no-claim policies, many profitable claim policies, or a material loss-making tail. This is more actionable than a plain count of policy types.\n\n# 7 Bivariate Mythbusting Analysis\n\n## 7.1 RQ1: Are Younger Drivers Genuinely Less Profitable Than Older Drivers?\n\n**Myth tested:** Young drivers are always the worst risks.\n\n**Technique justification:** A two-panel KPI chart bridges univariate and bivariate analysis: the first panel shows premium materiality by age band, while the second panel compares loss ratio and claim frequency. This prevents overreacting to a small segment that has high frequency but limited portfolio weight.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndriver_kpi_long <- driver_age_summary |>\n  select(driver_age_band, share_premium = premium, loss_ratio, claim_frequency) |>\n  mutate(share_premium = share_premium / sum(share_premium)) |>\n  pivot_longer(\n    cols = c(share_premium, loss_ratio, claim_frequency),\n    names_to = \"metric\",\n    values_to = \"value\"\n  ) |>\n  mutate(\n    metric = recode(\n      metric,\n      \"share_premium\" = \"Premium share\",\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\"\n    )\n  )\n\nggplot(driver_kpi_long, aes(metric, driver_age_band, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(\n    aes(label = if_else(metric == \"Claim frequency\", number(value, accuracy = 0.001), percent(value, accuracy = 0.1))),\n    size = 3\n  ) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number()) +\n  labs(\n    title = \"Driver age myth check: frequency is not the same as profitability\",\n    x = NULL,\n    y = \"Driver age band\",\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-14-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** The stereotype is **mixed**. Drivers aged 18-25 have the highest claim frequency (0.488), but their loss ratio is only 62.5% and they contribute just 1.0% of premium. The highest age-band loss ratio belongs to 26-35 at 73.3%.\n\n## 7.2 RQ2: Does Vehicle Age Increase Loss Ratio and Claim Frequency?\n\n**Myth tested:** Older vehicles are always riskier.\n\n**Technique justification:** Ranked KPI bars are used because the myth has two different dimensions: frequency and profitability. The chart shows whether the same vehicle-age band is worst on both.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvehicle_age_long <- vehicle_age_summary |>\n  select(vehicle_age_band, loss_ratio, claim_frequency, claim_severity) |>\n  pivot_longer(\n    cols = c(loss_ratio, claim_frequency, claim_severity),\n    names_to = \"metric\",\n    values_to = \"value\"\n  ) |>\n  mutate(\n    metric = recode(\n      metric,\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\",\n      \"claim_severity\" = \"Claim severity\"\n    )\n  )\n\nggplot(vehicle_age_long, aes(metric, vehicle_age_band, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(\n    aes(label = case_when(\n      metric == \"Claim severity\" ~ dollar(value, prefix = \"\"),\n      metric == \"Claim frequency\" ~ number(value, accuracy = 0.001),\n      TRUE ~ percent(value, accuracy = 0.1)\n    )),\n    size = 3\n  ) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number()) +\n  labs(\n    title = \"Vehicle age myth check: new vehicles claim often, mid-old vehicles lose more\",\n    x = NULL,\n    y = \"Vehicle age band\",\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-15-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** The stereotype is **partly real but incomplete**. Vehicles aged 0-3 have the highest claim frequency at 0.524, but the weakest loss ratio is 13-20 at 75.2%. Very old vehicles aged 21+ are more profitable than the stereotype suggests.\n\n## 7.3 RQ3: Which Policy Types Create the Most Profitability Pressure?\n\n**Myth tested:** Comprehensive policies are safer because customers pay more.\n\n**Technique justification:** A ranked loss-ratio bar with a break-even line is used because policy type is a compact product-design variable and the strategic action depends on whether the segment approaches or exceeds 100%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  policy_type_summary,\n  aes(x = \"Loss ratio\", y = fct_reorder(policy_type, loss_ratio), fill = loss_ratio)\n) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(aes(label = percent(loss_ratio, accuracy = 0.1)), size = 3.4) +\n  scale_fill_viridis_c(labels = percent_format(accuracy = 1), option = \"C\") +\n  labs(\n    title = \"Policy type myth check: higher cover does not guarantee stronger profitability\",\n    subtitle = \"Break-even reference is 100%; darker cells indicate higher loss ratio\",\n    x = NULL,\n    y = NULL,\n    fill = \"Loss ratio\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n**What this tells us:** The myth is **busted**. Comprehensive without excess has the weakest loss ratio at 93.9% and the highest claim frequency at 1.046. Premium adequacy and excess design need review.\n\n## 7.4 RQ4: Are Premium Vehicle Brands Less Profitable Than Mainstream Brands?\n\n**Myth tested:** Premium brands are the biggest loss drivers.\n\n**Technique justification:** A brand-tier KPI chart is used before brand-level analysis because it tests the status stereotype directly. It compares premium share, loss ratio, claim frequency, and severity in one readable view.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbrand_kpi_long <- brand_tier_summary |>\n  select(brand_tier, premium, loss_ratio, claim_frequency, claim_severity) |>\n  mutate(premium_share = premium / sum(premium)) |>\n  select(brand_tier, premium_share, loss_ratio, claim_frequency, claim_severity) |>\n  pivot_longer(-brand_tier, names_to = \"metric\", values_to = \"value\") |>\n  mutate(\n    metric = recode(\n      metric,\n      \"premium_share\" = \"Premium share\",\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\",\n      \"claim_severity\" = \"Claim severity\"\n    )\n  )\n\nggplot(brand_kpi_long, aes(metric, brand_tier, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(\n    aes(label = case_when(\n      metric == \"Claim severity\" ~ dollar(value, prefix = \"\"),\n      metric == \"Claim frequency\" ~ number(value, accuracy = 0.001),\n      TRUE ~ percent(value, accuracy = 0.1)\n    )),\n    size = 3\n  ) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number()) +\n  labs(\n    title = \"Brand prestige myth check\",\n    x = NULL,\n    y = NULL,\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-17-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** The myth is **mostly busted**. Premium brands have higher claim frequency (0.403) than mainstream brands, but their loss ratio is lower at 68.9% versus 70.7%. Premium brand status is a frequency signal, not the main profitability drain.\n\n## 7.5 RQ5: Does Vehicle Value Show a Monotonic Relationship With Loss Ratio?\n\n**Myth tested:** Higher vehicle value always means poorer profitability.\n\n**Technique justification:** Ordered bars by vehicle-value quintile show whether profitability worsens steadily with value. This is more direct than a scatterplot because the pricing question is about segment-level calibration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalue_long <- vehicle_value_summary |>\n  select(vehicle_value_band, loss_ratio, claim_frequency) |>\n  pivot_longer(-vehicle_value_band, names_to = \"metric\", values_to = \"value\") |>\n  mutate(metric = recode(metric, \"loss_ratio\" = \"Loss ratio\", \"claim_frequency\" = \"Claim frequency\"))\n\nggplot(value_long, aes(metric, vehicle_value_band, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(\n    aes(label = if_else(metric == \"Claim frequency\", number(value, accuracy = 0.001), percent(value, accuracy = 0.1))),\n    size = 3.1\n  ) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number()) +\n  labs(\n    title = \"Vehicle value myth check: the pattern is not monotonic\",\n    x = NULL,\n    y = \"Vehicle value quintile\",\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\n**What this tells us:** The myth is **mixed**. The highest-value band has high claim frequency (0.410) and a loss ratio of 73.3%, but the lowest-value band is also weak at 72.3%. Vehicle value should calibrate severity assumptions, not be treated as a one-direction rule.\n\n## 7.6 RQ6: Does Bonus Score Separate Profitable and Unprofitable Customers?\n\n**Myth tested:** Bad bonus-score customers are always the worst.\n\n**Technique justification:** `stat_halfeye()` shows distribution shape, `geom_boxplot()` shows compact spread, and pairwise Wilcoxon tests provide non-parametric evidence for differences across bonus-score groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  portfolio |> filter(!is.na(bonus_score), loss_ratio_capped_99 > 0),\n  aes(x = bonus_score, y = loss_ratio_capped_99, fill = bonus_score)\n) +\n  stat_halfeye(\n    adjust = 0.8, \n    width = 0.55, \n    justification = -0.2, \n    .width = 0, \n    alpha = 0.65, \n    show.legend = FALSE\n  ) +\n  geom_boxplot(\n    width = 0.16, \n    outlier.shape = NA, \n    alpha = 0.5, \n    show.legend = FALSE\n  ) +\n  geom_jitter(\n    width = 0.08, \n    alpha = 0.03, \n    size = 0.35, \n    show.legend = FALSE,\n    color = \"#2C3E50\" \n  ) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"#C0392B\", linewidth = 0.8) +\n  scale_y_continuous(labels = number_format(accuracy = 0.1)) +\n  scale_fill_brewer(palette = \"Set2\") +\n  theme_minimal(base_size = 14) +\n  labs(\n    title = \"Bonus Score Myth Check: Claim Severity\",\n    subtitle = \"Distribution of loss ratios (excluding zero-claim policies); dashed line = break-even\",\n    x = \"Bonus Score\",\n    y = \"Loss Ratio (Capped at 99th percentile)\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.wilcox.test(\n  x = portfolio$loss_ratio_capped_99,\n  g = portfolio$bonus_score,\n  p.adjust.method = \"holm\"\n)$p.value |>\n  as.data.frame() |>\n  rownames_to_column(\"Comparison\") |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Comparison | Good| Neutral|\n|:----------|----:|-------:|\n|Neutral    |    0|      NA|\n|Bad        |    0|       0|\n\n\n:::\n:::\n\n\n**What this tells us:** The myth is **mostly real, with nuance**. Bad bonus-score customers have the highest claim frequency at 0.624, but Neutral has the highest loss ratio at 81.4%. Good customers dominate premium volume and remain strategically important for retention.\n\n## 7.7 RQ7: Are Short-Exposure Policies a Hidden Profitability Problem?\n\n**Myth tested:** Short-term policies are harmless because exposure is small.\n\n**Technique justification:** `geom_density_ridges_gradient()` with quantile shading compares ordered exposure-duration distributions. This is better than a mean-only chart because the myth concerns hidden tail risk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  portfolio |> filter(claim_flag, !is.na(exposure_band), !is.na(loss_ratio_capped_99)),\n  aes(x = loss_ratio_capped_99, y = exposure_band, fill = factor(after_stat(quantile)))\n) +\n  geom_density_ridges_gradient(\n    calc_ecdf = TRUE,\n    quantiles = 4,\n    quantile_lines = TRUE,\n    scale = 1.8,\n    rel_min_height = 0.005\n  ) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", colour = \"grey40\") +\n  scale_fill_viridis_d(name = \"Quartile\", option = \"C\") +\n  scale_x_continuous(labels = number_format(accuracy = 0.1)) +\n  labs(\n    title = \"Exposure-duration myth check\",\n    subtitle = \"Claimants only; dashed line = break-even\",\n    x = \"Loss ratio capped at 99th percentile\",\n    y = \"Exposure band\"\n  ) +\n  theme_ridges(font_size = 11, grid = TRUE)\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\n**What this tells us:** The myth is **busted**. Very short policies have a loss ratio of 103.3%, the only exposure band above break-even. Although they contribute only 4.5% of premium, they are a strong quality-monitoring signal.\n\n## 7.8 RQ8: Are Longer-Observed Customers More Profitable and Worth Retaining?\n\n**Myth tested:** Loyal customers are just retained volume, not necessarily profitable.\n\n**Technique justification:** A loyalty-band KPI chart compares premium share, loss ratio, and cancellation rate. This directly links retention strategy to profitability, rather than treating loyalty as a volume metric only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloyalty_long <- loyalty_summary |>\n  select(loyalty_band, premium, loss_ratio, claim_frequency, cancel_rate = claim_rate) |>\n  mutate(premium_share = premium / sum(premium)) |>\n  select(loyalty_band, premium_share, loss_ratio, claim_frequency) |>\n  pivot_longer(-loyalty_band, names_to = \"metric\", values_to = \"value\") |>\n  mutate(\n    metric = recode(\n      metric,\n      \"premium_share\" = \"Premium share\",\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\"\n    )\n  )\n\nggplot(loyalty_long, aes(metric, loyalty_band, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(\n    aes(label = if_else(metric == \"Claim frequency\", number(value, accuracy = 0.001), percent(value, accuracy = 0.1))),\n    size = 3\n  ) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number()) +\n  labs(\n    title = \"Loyalty myth check: retained customers are materially more profitable\",\n    x = NULL,\n    y = \"Observed policy years in dataset\",\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-22-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** The myth is **busted**. Customers observed all 3 years have the best loss ratio at 63.4% and contribute 52.2% of premium. Retaining stable low-risk customers is directly aligned with profitability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(608)\nloyalty_between_data <- portfolio |>\n  filter(!is.na(loyalty_band), !is.na(loss_ratio_capped_99))\n\nloyalty_between_data <- loyalty_between_data |>\n  slice_sample(n = min(20000, nrow(loyalty_between_data)))\n\nggbetweenstats(\n  data = loyalty_between_data,\n  x = loyalty_band,\n  y = loss_ratio_capped_99,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  pairwise.display = \"significant\",\n  results.subtitle = FALSE,\n  title = \"Pairwise comparison of capped loss ratio by loyalty band\",\n  xlab = \"Observed policy years in dataset\",\n  ylab = \"Loss ratio capped at 99th percentile\"\n)\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n## 7.9 RQ9: Are Cancelled Policies Actually Worse Risks Than Active Policies?\n\n**Myth tested:** Cancelled policies are removed risks, so cancellation is good.\n\n**Technique justification:** A status KPI chart compares active and cancelled policies across loss ratio, frequency, severity, and premium share. This tests whether cancellation is associated with risk quality or just administrative status.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstatus_summary <- segment_summary(portfolio, policy_status)\n\nstatus_long <- status_summary |>\n  select(policy_status, premium, loss_ratio, claim_frequency, claim_severity) |>\n  mutate(premium_share = premium / sum(premium)) |>\n  select(policy_status, premium_share, loss_ratio, claim_frequency, claim_severity) |>\n  pivot_longer(-policy_status, names_to = \"metric\", values_to = \"value\") |>\n  mutate(\n    metric = recode(\n      metric,\n      \"premium_share\" = \"Premium share\",\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\",\n      \"claim_severity\" = \"Claim severity\"\n    )\n  )\n\nggplot(status_long, aes(metric, policy_status, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(\n    aes(label = case_when(\n      metric == \"Claim severity\" ~ dollar(value, prefix = \"\"),\n      metric == \"Claim frequency\" ~ number(value, accuracy = 0.001),\n      TRUE ~ percent(value, accuracy = 0.1)\n    )),\n    size = 3\n  ) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number()) +\n  labs(\n    title = \"Cancellation myth check\",\n    x = NULL,\n    y = \"Policy status\",\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-24-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** The myth is **real, but operationally important**. Cancelled policies have a loss ratio of 128.0% versus 64.4% for active policies. The insurer should identify these risks earlier, not only after cancellation has occurred.\n\n## 7.10 RQ10: Does Geography Materially Affect Frequency, Severity, and Loss Ratio?\n\n**Myth tested:** Urban areas are always worse than rural areas.\n\n**Technique justification:** Geography is assessed with circulation-area bars and geo-segment intervals. This separates frequency-driven urban risk from severity-driven rural risk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea_summary <- segment_summary(portfolio, circulation_area)\n\narea_long <- area_summary |>\n  select(circulation_area, loss_ratio, claim_frequency, claim_severity) |>\n  pivot_longer(-circulation_area, names_to = \"metric\", values_to = \"value\") |>\n  mutate(\n    metric = recode(\n      metric,\n      \"loss_ratio\" = \"Loss ratio\",\n      \"claim_frequency\" = \"Claim frequency\",\n      \"claim_severity\" = \"Claim severity\"\n    )\n  )\n\nggplot(area_long, aes(metric, circulation_area, fill = value)) +\n  geom_tile(colour = \"white\", linewidth = 0.5) +\n  geom_text(\n    aes(label = case_when(\n      metric == \"Claim severity\" ~ dollar(value, prefix = \"\"),\n      metric == \"Claim frequency\" ~ number(value, accuracy = 0.001),\n      TRUE ~ percent(value, accuracy = 0.1)\n    )),\n    size = 3.1\n  ) +\n  scale_fill_viridis_c(option = \"C\", labels = label_number()) +\n  labs(\n    title = \"Urban-rural myth check\",\n    x = NULL,\n    y = \"Circulation area\",\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-25-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** The myth is **mostly real for frequency but mixed for severity**. Urban policies have higher claim frequency (0.335) and loss ratio (71.4%), while rural policies have higher severity (995.91). Urban pricing should focus on frequency; rural review should pay attention to severity.\n\n# 8 Multivariate Analysis\n\n## 8.1 Which Driver-Age and Vehicle-Age Combinations Elevate Claim Risk?\n\n**Research question:** Which driver-age and vehicle-age combinations elevate claim risk?\n\n**Technique justification:** A heatmap is the most compact way to show a two-way interaction. Embedded labels make the answer readable without requiring the viewer to inspect a colour legend alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_heatmap <- portfolio |>\n  filter(!is.na(driver_age_band), !is.na(vehicle_age_band)) |>\n  group_by(driver_age_band, vehicle_age_band) |>\n  summarise(\n    exposure = sum(total_exposure, na.rm = TRUE),\n    claims = sum(total_claims, na.rm = TRUE),\n    claim_frequency = claims / exposure,\n    .groups = \"drop\"\n  )\n\nggplot(age_heatmap, aes(vehicle_age_band, driver_age_band, fill = claim_frequency)) +\n  geom_tile(colour = \"white\", linewidth = 0.4) +\n  geom_text(aes(label = number(claim_frequency, accuracy = 0.01)), size = 3) +\n  scale_fill_viridis_c(option = \"C\", labels = number_format(accuracy = 0.01)) +\n  labs(\n    title = \"Claim frequency by driver age and vehicle age\",\n    x = \"Vehicle age band\",\n    y = \"Driver age band\",\n    fill = \"Claim frequency\"\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-26-1.png){width=960}\n:::\n:::\n\n\n**What this tells us:** The interaction view identifies combinations that can be missed when driver age and vehicle age are analysed separately. These cells are candidates for refined underwriting rules or pricing interactions.\n\n## 8.2 Do Brand, Value, and Power-to-Weight Signals Identify Severity Risk?\n\n**Research question:** Do brand, value, and power-to-weight signals identify severity risk?\n\n**Technique justification:** A point-interval chart compares brand tiers with uncertainty, while a hexbin plus GAM smoother handles dense policy-level numeric data without overplotting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_brand_tier <- ggplot(\n  portfolio |>\n    filter(claim_flag, !is.na(brand_tier), !is.na(claim_severity), claim_severity > 0),\n  aes(x = brand_tier, y = claim_severity)\n) +\n  stat_pointinterval(\n    .width = c(0.8, 0.95),\n    point_size = 3,\n    aes(colour = factor(after_stat(.width)))\n  ) +\n  scale_y_log10(labels = dollar_format(prefix = \"\")) +\n  scale_colour_manual(\n    values = c(\"0.8\" = \"#4C78A8\", \"0.95\" = \"#F58518\"),\n    labels = c(\"80% interval\", \"95% interval\"),\n    name = NULL\n  ) +\n  labs(title = \"Claim severity by brand tier\", x = NULL, y = \"Claim severity\")\n\np_power <- ggplot(\n  portfolio |>\n    filter(\n      !is.na(power_to_weight_ratio),\n      !is.na(loss_ratio_capped_99),\n      power_to_weight_ratio > 0\n    ),\n  aes(power_to_weight_ratio, loss_ratio_capped_99)\n) +\n  geom_hex(bins = 35) +\n  geom_smooth(method = \"gam\", formula = y ~ s(x, bs = \"cs\"), colour = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(labels = comma, option = \"C\") +\n  labs(\n    title = \"Power-to-weight versus loss ratio\",\n    x = \"Power-to-weight ratio\",\n    y = \"Loss ratio\",\n    fill = \"Records\"\n  )\n\np_brand_tier | p_power\n```\n\n::: {.cell-output-display}\n![](TH_EX01_deliverable_files/figure-html/unnamed-chunk-27-1.png){width=1056}\n:::\n:::\n\n\n**What this tells us:** Brand and vehicle-performance signals should be treated as severity or tail-risk indicators only if they show visible separation after considering uncertainty and dense-record patterns.\n\n## 8.3 Which Segments Should Be Reviewed First?\n\n**Research questions supported:** RQ1 to RQ10.\n\n**Technique justification:** A priority table turns the visual findings into an action queue. It combines loss ratio, frequency, severity, premium materiality, and evidence strength so the report ends with a decision-oriented output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npriority_tbl <- bind_rows(\n  policy_type_summary |> transmute(segment_type = \"Policy type\", segment = as.character(policy_type), premium, loss_ratio, claim_frequency, claim_severity),\n  segment_summary(portfolio, policy_status) |> transmute(segment_type = \"Policy status\", segment = as.character(policy_status), premium, loss_ratio, claim_frequency, claim_severity),\n  bonus_summary |> transmute(segment_type = \"Bonus score\", segment = as.character(bonus_score), premium, loss_ratio, claim_frequency, claim_severity),\n  exposure_summary |> transmute(segment_type = \"Exposure band\", segment = as.character(exposure_band), premium, loss_ratio, claim_frequency, claim_severity),\n  driver_age_summary |> transmute(segment_type = \"Driver age\", segment = as.character(driver_age_band), premium, loss_ratio, claim_frequency, claim_severity),\n  vehicle_age_summary |> transmute(segment_type = \"Vehicle age\", segment = as.character(vehicle_age_band), premium, loss_ratio, claim_frequency, claim_severity),\n  vehicle_value_summary |> transmute(segment_type = \"Vehicle value\", segment = as.character(vehicle_value_band), premium, loss_ratio, claim_frequency, claim_severity),\n  brand_tier_summary |> transmute(segment_type = \"Brand tier\", segment = as.character(brand_tier), premium, loss_ratio, claim_frequency, claim_severity),\n  loyalty_summary |> transmute(segment_type = \"Loyalty\", segment = as.character(loyalty_band), premium, loss_ratio, claim_frequency, claim_severity),\n  geo_summary |> transmute(segment_type = \"Geography\", segment = as.character(geo_segment), premium, loss_ratio, claim_frequency, claim_severity)\n) |>\n  filter(!is.na(segment), premium > 0) |>\n  mutate(\n    materiality_score = percent_rank(premium),\n    loss_score = percent_rank(loss_ratio),\n    frequency_score = percent_rank(claim_frequency),\n    severity_score = percent_rank(replace_na(claim_severity, 0)),\n    priority_score = 0.35 * loss_score + 0.25 * frequency_score +\n      0.20 * severity_score + 0.20 * materiality_score\n  ) |>\n  arrange(desc(priority_score)) |>\n  slice_head(n = 12)\n\npriority_tbl |>\n  transmute(\n    Rank = row_number(),\n    `Segment type` = segment_type,\n    Segment = segment,\n    Premium = dollar(premium, prefix = \"\"),\n    `Loss ratio` = percent(loss_ratio, accuracy = 0.1),\n    `Claim frequency` = number(claim_frequency, accuracy = 0.001),\n    `Claim severity` = dollar(claim_severity, prefix = \"\"),\n    `Priority score` = number(priority_score, accuracy = 0.01)\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| Rank|Segment type  |Segment                      |Premium    |Loss ratio |Claim frequency |Claim severity |Priority score |\n|----:|:-------------|:----------------------------|:----------|:----------|:---------------|:--------------|:--------------|\n|    1|Policy status |Cancelled                    |9,679,856  |128.0%     |0.506           |1,213.07       |0.83           |\n|    2|Exposure band |Very short (<0.35)           |4,768,791  |103.3%     |0.347           |1,259.19       |0.75           |\n|    3|Bonus score   |Bad                          |2,786,084  |79.0%      |0.624           |1,145.18       |0.74           |\n|    4|Bonus score   |Neutral                      |3,268,691  |81.4%      |0.478           |1,140.55       |0.73           |\n|    5|Policy type   |Comprehensive with excess    |35,712,392 |73.8%      |0.410           |988.01         |0.72           |\n|    6|Vehicle value |Highest                      |28,700,748 |73.3%      |0.410           |1,013.96       |0.71           |\n|    7|Loyalty       |Observed 1 year              |13,043,675 |88.2%      |0.297           |1,167.19       |0.67           |\n|    8|Loyalty       |Observed 2 years             |37,211,398 |74.1%      |0.320           |972.47         |0.66           |\n|    9|Exposure band |Short (0.35-0.75)            |20,894,148 |75.1%      |0.305           |1,029.49       |0.66           |\n|   10|Policy type   |Comprehensive without excess |10,344,550 |93.9%      |1.046           |752.25         |0.65           |\n|   11|Vehicle age   |13-20                        |23,135,053 |75.2%      |0.326           |924.57         |0.62           |\n|   12|Vehicle age   |0-3                          |1,453,607  |70.8%      |0.524           |1,179.46       |0.60           |\n\n\n:::\n:::\n\n\n**What this tells us:** The priority table prevents overreacting to visually interesting but immaterial segments. Review should start where adverse performance and portfolio materiality overlap.\n\n## 8.4 Statistical Validation\n\n**Technique justification:** Statistical tests are used as directional validation, not as a replacement for visual interpretation. With a large dataset, very small differences can become statistically significant, so practical significance still depends on visual effect size and premium exposure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkw_test <- function(variable) {\n  formula <- as.formula(str_c(\"loss_ratio_capped_99 ~ \", variable))\n  kruskal.test(formula, data = portfolio) |>\n    tidy() |>\n    mutate(test = \"Kruskal-Wallis\", variable = variable)\n}\n\nchisq_test <- function(variable) {\n  tbl <- table(portfolio[[variable]], portfolio$claim_flag)\n  chisq.test(tbl) |>\n    tidy() |>\n    mutate(test = \"Chi-square\", variable = variable)\n}\n\nspearman_test <- function(variable) {\n  cor.test(\n    portfolio[[variable]],\n    portfolio$loss_ratio_capped_99,\n    method = \"spearman\",\n    exact = FALSE\n  ) |>\n    tidy() |>\n    mutate(test = \"Spearman\", variable = variable)\n}\n\nvalidation_tbl <- bind_rows(\n  map_dfr(\n    c(\"policy_type\", \"business_type\", \"policy_status\", \"bonus_score\",\n      \"exposure_band\", \"driver_age_band\", \"vehicle_age_band\", \"vehicle_value_band\",\n      \"brand_tier\", \"loyalty_band\", \"geo_segment\"),\n    kw_test\n  ),\n  map_dfr(\n    c(\"policy_type\", \"business_type\", \"policy_status\", \"bonus_score\",\n      \"exposure_band\", \"driver_age_band\", \"vehicle_age_band\", \"vehicle_value_band\",\n      \"brand_tier\", \"loyalty_band\", \"geo_segment\"),\n    chisq_test\n  ),\n  map_dfr(\n    c(\"driver_age\", \"vehicle_age\", \"vehicle_value\", \"power_to_weight_ratio\"),\n    spearman_test\n  )\n) |>\n  transmute(\n    test,\n    variable,\n    statistic = round(statistic, 3),\n    estimate = round(estimate, 3),\n    p_value = p.value\n  ) |>\n  arrange(p_value)\n\nvalidation_tbl |>\n  mutate(p_value = pvalue(p_value, accuracy = 0.001)) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|test           |variable              |    statistic| estimate|p_value |\n|:--------------|:---------------------|------------:|--------:|:-------|\n|Kruskal-Wallis |policy_type           | 7.303954e+03|       NA|<0.001  |\n|Kruskal-Wallis |business_type         | 2.002126e+03|       NA|<0.001  |\n|Kruskal-Wallis |exposure_band         | 7.429852e+03|       NA|<0.001  |\n|Kruskal-Wallis |vehicle_value_band    | 1.602394e+03|       NA|<0.001  |\n|Chi-square     |policy_type           | 6.638421e+03|       NA|<0.001  |\n|Chi-square     |business_type         | 2.317924e+03|       NA|<0.001  |\n|Chi-square     |exposure_band         | 9.687787e+03|       NA|<0.001  |\n|Chi-square     |vehicle_value_band    | 1.626012e+03|       NA|<0.001  |\n|Chi-square     |loyalty_band          | 1.563811e+03|       NA|<0.001  |\n|Spearman       |vehicle_value         | 6.848907e+15|    0.070|<0.001  |\n|Kruskal-Wallis |loyalty_band          | 1.182240e+03|       NA|<0.001  |\n|Chi-square     |brand_tier            | 5.399690e+02|       NA|<0.001  |\n|Kruskal-Wallis |brand_tier            | 5.231160e+02|       NA|<0.001  |\n|Kruskal-Wallis |geo_segment           | 4.644370e+02|       NA|<0.001  |\n|Chi-square     |driver_age_band       | 4.632710e+02|       NA|<0.001  |\n|Spearman       |power_to_weight_ratio | 7.655275e+15|   -0.035|<0.001  |\n|Chi-square     |vehicle_age_band      | 4.370260e+02|       NA|<0.001  |\n|Chi-square     |geo_segment           | 4.271950e+02|       NA|<0.001  |\n|Spearman       |vehicle_age           | 7.612285e+15|   -0.029|<0.001  |\n|Chi-square     |bonus_score           | 2.971860e+02|       NA|<0.001  |\n|Kruskal-Wallis |vehicle_age_band      | 3.035070e+02|       NA|<0.001  |\n|Kruskal-Wallis |bonus_score           | 2.874290e+02|       NA|<0.001  |\n|Kruskal-Wallis |driver_age_band       | 2.670180e+02|       NA|<0.001  |\n|Spearman       |driver_age            | 7.586603e+15|   -0.025|<0.001  |\n|Kruskal-Wallis |policy_status         | 1.901320e+02|       NA|<0.001  |\n|Chi-square     |policy_status         | 7.247800e+01|       NA|<0.001  |\n\n\n:::\n:::\n\n\n**What this tells us:** Statistical validation supports the segmentation exercise, but the business decision should be based on the combination of statistical evidence, visible effect size, and premium exposure.\n\n# 9 Summary of Key Findings and Answers to the 10 Research Questions\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndriver_young <- driver_age_summary |> filter(driver_age_band == \"18-25\")\ndriver_loss_top <- driver_age_summary |> slice_max(loss_ratio, n = 1, with_ties = FALSE)\n\nvehicle_new <- vehicle_age_summary |> filter(vehicle_age_band == \"0-3\")\nvehicle_loss_top <- vehicle_age_summary |> slice_max(loss_ratio, n = 1, with_ties = FALSE)\nvehicle_old <- vehicle_age_summary |> filter(vehicle_age_band == \"21+\")\n\ncomp_no_excess <- policy_type_summary |> filter(policy_type == \"Comprehensive without excess\")\ncomp_with_excess <- policy_type_summary |> filter(policy_type == \"Comprehensive with excess\")\n\npremium_brand <- brand_tier_summary |> filter(brand_tier == \"Premium brand\")\nmainstream_brand <- brand_tier_summary |> filter(brand_tier == \"Mainstream brand\")\n\nvalue_highest <- vehicle_value_summary |> filter(vehicle_value_band == \"Highest\")\nvalue_lowest <- vehicle_value_summary |> filter(vehicle_value_band == \"Lowest\")\nvalue_best <- vehicle_value_summary |> slice_min(loss_ratio, n = 1, with_ties = FALSE)\n\nbonus_good <- bonus_summary |> filter(bonus_score == \"Good\")\nbonus_neutral <- bonus_summary |> filter(bonus_score == \"Neutral\")\nbonus_bad <- bonus_summary |> filter(bonus_score == \"Bad\")\n\nexposure_very_short <- exposure_summary |> filter(exposure_band == \"Very short (<0.35)\")\nexposure_full <- exposure_summary |> filter(exposure_band == \"Full (>0.95)\")\n\nloyal_3yr <- loyalty_summary |> filter(loyalty_band == \"Observed all 3 years\")\nloyal_1yr <- loyalty_summary |> filter(loyalty_band == \"Observed 1 year\")\n\nstatus_summary <- segment_summary(portfolio, policy_status)\nstatus_cancelled <- status_summary |> filter(policy_status == \"Cancelled\")\nstatus_active <- status_summary |> filter(policy_status == \"Active\")\n\narea_summary <- segment_summary(portfolio, circulation_area)\narea_urban <- area_summary |> filter(circulation_area == \"Urban\")\narea_rural <- area_summary |> filter(circulation_area == \"Rural\")\n\nanswer_tbl <- tibble(\n  `Myth verdict` = c(\n    \"Mixed\",\n    \"Partly real\",\n    \"Busted\",\n    \"Mostly busted\",\n    \"Mixed\",\n    \"Mostly real\",\n    \"Busted\",\n    \"Busted\",\n    \"Real, but reactive\",\n    \"Mixed\"\n  ),\n  `Research question` = c(\n    \"RQ1. Are younger drivers genuinely less profitable than older drivers?\",\n    \"RQ2. Does vehicle age increase loss ratio and claim frequency?\",\n    \"RQ3. Which policy types create the most profitability pressure?\",\n    \"RQ4. Are premium vehicle brands less profitable than mainstream brands?\",\n    \"RQ5. Does vehicle value show a monotonic relationship with loss ratio?\",\n    \"RQ6. Does bonus score separate profitable and unprofitable customers?\",\n    \"RQ7. Are short-exposure policies a hidden profitability problem?\",\n    \"RQ8. Are longer-observed customers more profitable and worth retaining?\",\n    \"RQ9. Are cancelled policies actually worse risks than active policies?\",\n    \"RQ10. Does geography materially affect frequency, severity, and loss ratio?\"\n  ),\n  `Answer and implication` = c(\n    str_glue(\"Young drivers have the highest frequency ({number(driver_young$claim_frequency, accuracy = 0.001)}) but only {percent(driver_young$loss_ratio, accuracy = 0.1)} loss ratio and {percent(driver_young$premium / sum(driver_age_summary$premium), accuracy = 0.1)} of premium. The weakest age-band loss ratio is {driver_loss_top$driver_age_band} at {percent(driver_loss_top$loss_ratio, accuracy = 0.1)}.\"),\n    str_glue(\"New vehicles aged 0-3 have the highest frequency ({number(vehicle_new$claim_frequency, accuracy = 0.001)}), but the worst loss ratio is {vehicle_loss_top$vehicle_age_band} at {percent(vehicle_loss_top$loss_ratio, accuracy = 0.1)}. Vehicles aged 21+ are more profitable at {percent(vehicle_old$loss_ratio, accuracy = 0.1)}.\"),\n    str_glue(\"Comprehensive without excess is the clearest pressure point: {percent(comp_no_excess$loss_ratio, accuracy = 0.1)} loss ratio and {number(comp_no_excess$claim_frequency, accuracy = 0.001)} claim frequency. Comprehensive with excess is also material at {percent(comp_with_excess$premium / sum(policy_type_summary$premium), accuracy = 0.1)} of premium.\"),\n    str_glue(\"Premium brands have higher frequency ({number(premium_brand$claim_frequency, accuracy = 0.001)}) but lower loss ratio ({percent(premium_brand$loss_ratio, accuracy = 0.1)}) than mainstream brands ({percent(mainstream_brand$loss_ratio, accuracy = 0.1)}). Brand prestige is not the main loss driver.\"),\n    str_glue(\"The highest-value band has {percent(value_highest$loss_ratio, accuracy = 0.1)} loss ratio, but the lowest-value band is also weak at {percent(value_lowest$loss_ratio, accuracy = 0.1)}. The best band is {value_best$vehicle_value_band} at {percent(value_best$loss_ratio, accuracy = 0.1)}, so the pattern is not monotonic.\"),\n    str_glue(\"Bad bonus-score policies have the highest frequency ({number(bonus_bad$claim_frequency, accuracy = 0.001)}), while Neutral has the highest loss ratio ({percent(bonus_neutral$loss_ratio, accuracy = 0.1)}). Good policies form {percent(bonus_good$premium / sum(bonus_summary$premium), accuracy = 0.1)} of premium and remain the loyalty base.\"),\n    str_glue(\"Very short policies have {percent(exposure_very_short$loss_ratio, accuracy = 0.1)} loss ratio, above break-even, versus {percent(exposure_full$loss_ratio, accuracy = 0.1)} for full-exposure policies. Short exposure is a quality signal despite small premium share.\"),\n    str_glue(\"Customers observed all 3 years have the best loss ratio ({percent(loyal_3yr$loss_ratio, accuracy = 0.1)}) and {percent(loyal_3yr$premium / sum(loyalty_summary$premium), accuracy = 0.1)} of premium. One-year customers are weakest at {percent(loyal_1yr$loss_ratio, accuracy = 0.1)}.\"),\n    str_glue(\"Cancelled policies are materially worse: {percent(status_cancelled$loss_ratio, accuracy = 0.1)} loss ratio and {number(status_cancelled$claim_frequency, accuracy = 0.001)} frequency versus {percent(status_active$loss_ratio, accuracy = 0.1)} and {number(status_active$claim_frequency, accuracy = 0.001)} for active policies.\"),\n    str_glue(\"Urban policies have higher frequency ({number(area_urban$claim_frequency, accuracy = 0.001)}) and loss ratio ({percent(area_urban$loss_ratio, accuracy = 0.1)}), while rural policies have higher severity ({dollar(area_rural$claim_severity, prefix = '')}). Geography affects risk, but the mechanism differs.\")\n  )\n)\n\nanswer_tbl |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Myth verdict       |Research question                                                           |Answer and implication                                                                                                                                                          |\n|:------------------|:---------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n|Mixed              |RQ1. Are younger drivers genuinely less profitable than older drivers?      |Young drivers have the highest frequency (0.488) but only 62.5% loss ratio and 1.0% of premium. The weakest age-band loss ratio is 26-35 at 73.3%.                              |\n|Partly real        |RQ2. Does vehicle age increase loss ratio and claim frequency?              |New vehicles aged 0-3 have the highest frequency (0.524), but the worst loss ratio is 13-20 at 75.2%. Vehicles aged 21+ are more profitable at 67.7%.                           |\n|Busted             |RQ3. Which policy types create the most profitability pressure?             |Comprehensive without excess is the clearest pressure point: 93.9% loss ratio and 1.046 claim frequency. Comprehensive with excess is also material at 34.0% of premium.        |\n|Mostly busted      |RQ4. Are premium vehicle brands less profitable than mainstream brands?     |Premium brands have higher frequency (0.403) but lower loss ratio (68.9%) than mainstream brands (70.7%). Brand prestige is not the main loss driver.                           |\n|Mixed              |RQ5. Does vehicle value show a monotonic relationship with loss ratio?      |The highest-value band has 73.3% loss ratio, but the lowest-value band is also weak at 72.3%. The best band is High at 67.1%, so the pattern is not monotonic.                  |\n|Mostly real        |RQ6. Does bonus score separate profitable and unprofitable customers?       |Bad bonus-score policies have the highest frequency (0.624), while Neutral has the highest loss ratio (81.4%). Good policies form 94.2% of premium and remain the loyalty base. |\n|Busted             |RQ7. Are short-exposure policies a hidden profitability problem?            |Very short policies have 103.3% loss ratio, above break-even, versus 65.7% for full-exposure policies. Short exposure is a quality signal despite small premium share.          |\n|Busted             |RQ8. Are longer-observed customers more profitable and worth retaining?     |Customers observed all 3 years have the best loss ratio (63.4%) and 52.2% of premium. One-year customers are weakest at 88.2%.                                                  |\n|Real, but reactive |RQ9. Are cancelled policies actually worse risks than active policies?      |Cancelled policies are materially worse: 128.0% loss ratio and 0.506 frequency versus 64.4% and 0.291 for active policies.                                                      |\n|Mixed              |RQ10. Does geography materially affect frequency, severity, and loss ratio? |Urban policies have higher frequency (0.335) and loss ratio (71.4%), while rural policies have higher severity (995.91). Geography affects risk, but the mechanism differs.     |\n\n\n:::\n:::\n\n\nThe overall conclusion is that several common insurance stereotypes are only partially true. The strongest strategic signals are policy type, exposure duration, cancellation status, loyalty duration, and bonus score. Age, vehicle age, brand prestige, vehicle value, and geography matter, but they should be used as calibrated segmentation features rather than blunt stereotypes.\n\n# 10 References\n\n- Data source: Mendeley Data, motor vehicle insurance portfolio dataset and accompanying cookbook.\n- Wickham, H. et al. *R for Data Science* and the tidyverse documentation.\n- Wilke, C. O. *Fundamentals of Data Visualization* and `ggridges` documentation.\n- Kay, M. `ggdist`: visualisations of distributions and uncertainty.\n- Wickham, H. *ggplot2: Elegant Graphics for Data Analysis*.\n- ISSS608 course materials on visual analytics and exploratory data analysis.",
    "supporting": [
      "TH_EX01_deliverable_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}